name: buchshelfly
description: "An improved cross-platform app for Audiobookshelf"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0

  # Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1


  # Misc
  uuid: ^4.5.1
  intl: ^0.20.2

  sembast: ^3.8.5+1

  # Core
  just_audio: ^0.10.3 # Should be setup for Android, Windows, iOS, macOS, Linux | Testing needed for iOS, macOS, Linux | https://pub.dev/packages/just_audio
  audio_service: ^0.18.18 # Should be setup for Android, Windows, iOS | Testing needed for iOS, macOS | for macOS pod is needed platform :osx, '10.12.2' | https://pub.dev/packages/audio_service
  dio: ^5.8.0+1
  drift: ^2.26.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.32
  cached_network_image: ^3.4.1
  go_router: ^15.1.2

  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  connectivity_plus: ^6.1.4
  rxdart: ^0.28.0
  background_downloader: ^9.2.2 # iOS needs background fetch | Testing needed for iOS, Android | https://pub.dev/packages/background_downloader

  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  sensors_plus: ^6.1.1 # Should be setup for Android, iOS, macOS, Windows | Testing needed for iOS, macOS, Windows | https://pub.dev/packages/sensors_plus
  vibration: ^3.1.3

  # Note for contributors: Commit pinning is used. Please check for updates when updating the e-Reader. This is for security, as it runs in a WebView and the repository is very small.
  flutter_epub_reader:
    git:
      url: https://github.com/chandrabezzo/epub_viewer.git
      ref: db2bab1bf511e4191a362014dbfc3067a16dd220

  ## Platform
  just_audio_media_kit: ^2.1.0

  ## Windows
  media_kit_libs_windows_audio: any

  ## Linux
  audio_service_mpris: ^0.2.0 # Needs to be tested

  ## MacOS

  ## iOS

  ## Android

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  drift_dev: ^2.26.1
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
