name: Check requirements
description: Run checks to determine if build should proceed

runs:
  using: composite
  steps:
    # For context for contributors:
    # The flatpak run depends on the launchpad PPA, because Ubuntu 24.04 does not ship with the latest flatpak-builder
    # Thus the PPA repo is needed. At the time of writing (05.05.2026) Canonical has massive issues with providing stable connection
    # For now over 4 days. To not spend useless resources, this check needs to be passed before doing anything else.
    # Once GitHub runners support Ubuntu 26 this is not required anymore. The addition of the ppa should then also be removed from that build step
    - name: Check if launchpad is reachable
      shell: bash
      run: |
        if ! curl -sSf https://ppa.launchpadcontent.net/flatpak/stable/ubuntu > /dev/null; then
          echo "Launchpad API is not reachable"
          exit 1
        fi

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Check formatting
      shell: bash
      run: dart format --set-exit-if-changed lib

    - name: Check generated files
      shell: bash
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Format
      shell: bash
      run: dart format lib

    - name: Check if files changed
      shell: bash
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Generated files are not up to date. Please run 'dart run build_runner build --delete-conflicting-outputs' and commit the changes."
          exit 1
        fi

    - name: intl_utils
      shell: bash
      run: dart run intl_utils:generate

    - name: Format
      shell: bash
      run: dart format lib

    - name: Check if files changed
      shell: bash
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Generated files are not up to date. Please run 'dart run intl_utils:generate' and commit the changes."
          exit 1
        fi

    - name: Add arb_utils
      shell: bash
      run: dart pub global activate arb_utils

    - name: Get all .arb files in lib/l10n and run arb_utils sort lib/l10n/*.arb
      shell: bash
      run: |
        for file in lib/l10n/*.arb; do
          arb_utils sort "$file"
          arb_utils generate-meta "$file"
        done

    - name: Format
      shell: bash
      run: dart format lib

    - name: Check if files changed
      shell: bash
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Generated files are not up to date. Please run 'arb_utils sort' and 'arb_utils generate-meta' and commit the changes."
          exit 1
        fi

    - name: Check if flutter fixes are available
      shell: bash
      run: dart fix lib/ --dry-run | grep "Nothing to fix!" || (echo "Flutter fixes are
        available. Please run 'dart fix . --apply' and commit the changes." &&
        exit 1)

    - name: Check if errors are present
      shell: bash
      run: flutter analyze lib | grep "No issues found!" || (echo "Analyzer found issues in yaabsa sources. Please fix them and commit the changes." && exit 1)