app_id: 5A1397DE-0D70-4E1D-918D-0F9959BD1E8C
publisher: Vito0912
publisher_url: https://github.com/Vito0912/yaabsa
display_name: yaabsa
create_desktop_icon: false
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
# setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - de